### ISSUE TITLE
no such file or directory (ffmpegsumo.dll)

### ISSUE THREAD

**Issue by johnhuffsmith** [brzpegasus/ember-cli-nwjs#45]
Starting with a new ember project, `ember nw:package` fails with the following error: `ENOENT, no such file or directory '/Users/john/Desktop/nwjstest/build/cache/0.13.0-alpha3/win64/ffmpegsumo.dll'` when trying to package either `win64` or `win32`

Full output:
```
Johns-iMac:nwjstest john$ ember nw:package
version: 1.13.8
Built project successfully. Stored in "dist/".
Packaging...
Latest Version: v0.13.0-alpha3
Using v0.13.0-alpha3
Create cache folder in /Users/john/Desktop/nwjstest/build/cache/0.13.0-alpha3
Downloading: http://dl.nwjs.io/v0.13.0-alpha3/nwjs-v0.13.0-alpha3-win-x64.zip
  downloading [====================] 100% 0.0s

Create release folder in /Users/john/Desktop/nwjstest/build/app/0.0.0/win64
ENOENT, no such file or directory '/Users/john/Desktop/nwjstest/build/cache/0.13.0-alpha3/win64/ffmpegsumo.dll'
Error: ENOENT, no such file or directory '/Users/john/Desktop/nwjstest/build/cache/0.13.0-alpha3/win64/ffmpegsumo.dll'
    at Error (native)
    at Object.fs.lstatSync (fs.js:796:18)
    at /Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/lib/utils.js:86:28
    at tryCatch2 (/Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/node_modules/bluebird/js/main/util.js:73:19)
    at Promise$_resolveFromResolver [as _resolveFromResolver] (/Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/node_modules/bluebird/js/main/promise.js:595:13)
    at new Promise (/Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/node_modules/bluebird/js/main/promise.js:87:37)
    at Object.module.exports.copyFile (/Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/lib/utils.js:85:16)
    at /Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/lib/index.js:351:36
    at Array.forEach (native)
    at /Users/john/Desktop/nwjstest/node_modules/ember-cli-nwjs/node_modules/nw-builder/lib/index.js:343:24

```

**Comment by brzpegasus** [comment]
Interesting. Does it work with a different version of the nwjs binary (maybe a non-alpha version)? You can change the version used to build in `config/nw-package`.

**Comment by johnhuffsmith** [comment]
Thanks!  Works after adding `version: '0.12.2'` to my `config/nw-package`.
